package com.mrcaracal.havadurumumrc.viewmodel

import android.util.Log
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import com.google.android.gms.maps.CameraUpdateFactory
import com.google.android.gms.maps.model.LatLng
import com.google.android.gms.maps.model.MarkerOptions
import com.mrcaracal.havadurumumrc.model.WeatherModel
import com.mrcaracal.havadurumumrc.service.WeatherAPIService
import io.reactivex.android.schedulers.AndroidSchedulers
import io.reactivex.disposables.CompositeDisposable
import io.reactivex.observers.DisposableSingleObserver
import io.reactivex.schedulers.Schedulers
import kotlin.collections.ArrayList

private const val TAG = "MainViewModel"

class MainViewModel : ViewModel() {

    private val weatherApiService = WeatherAPIService()
    private val disposable = CompositeDisposable()

    val weather_data = MutableLiveData<WeatherModel>()
    val weather_error = MutableLiveData<Boolean>()
    val weather_loading = MutableLiveData<Boolean>()

    fun refreshData(cityName: String) {
        getDataFromAPI(cityName)
    }

    private fun getDataFromAPI(cityName: String) {

        weather_loading.value = true
        disposable.add(
            weatherApiService.getDataService(cityName)
                .subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(object : DisposableSingleObserver<WeatherModel>() {

                    override fun onSuccess(t: WeatherModel) {
                        weather_data.value = t
                        weather_error.value = false
                        weather_loading.value = false
                        Log.d(TAG, "onSuccess: Success")
                    }

                    override fun onError(e: Throwable) {
                        weather_error.value = true
                        weather_loading.value = false
                        Log.e(TAG, "onError: " + e)
                    }

                })
        )

    }

    fun loadAllCities(): ArrayList<String> {
        val citiesList = ArrayList<String>()
        citiesList.add("adana")
        citiesList.add("adiyaman")
        citiesList.add("afyonkarahisar")
        citiesList.add("agri")
        citiesList.add("aksaray")
        citiesList.add("amasya")
        citiesList.add("ankara")
        citiesList.add("antalya")
        citiesList.add("ardahan")
        citiesList.add("artvin")
        citiesList.add("aydin")
        citiesList.add("balikesir")
        citiesList.add("bartin")
        citiesList.add("batman")
        citiesList.add("bayburt")
        citiesList.add("bilecik")
        citiesList.add("bingol")
        citiesList.add("bitlis")
        citiesList.add("bolu")
        citiesList.add("burdur")
        citiesList.add("bursa")
        citiesList.add("canakkale")
        citiesList.add("cankiri")
        citiesList.add("corum")
        citiesList.add("denizli")
        citiesList.add("diyarbakir")
        citiesList.add("duzce")
        citiesList.add("edirne")
        citiesList.add("elazig")
        citiesList.add("erzincan")
        citiesList.add("erzurum")
        citiesList.add("eskisehir")
        citiesList.add("gaziantep")
        citiesList.add("giresun")
        citiesList.add("gumushane")
        citiesList.add("hakkâri")
        citiesList.add("hatay")
        citiesList.add("igdir")
        citiesList.add("isparta")
        citiesList.add("istanbul")
        citiesList.add("izmir")
        citiesList.add("kahramanmaras")
        citiesList.add("karabuk")
        citiesList.add("karaman")
        citiesList.add("kars")
        citiesList.add("kastamonu")
        citiesList.add("kayseri")
        citiesList.add("kilis")
        citiesList.add("kirikkale")
        citiesList.add("kirklareli")
        citiesList.add("kirsehir")
        citiesList.add("kocaeli")
        citiesList.add("konya")
        citiesList.add("kutahya")
        citiesList.add("malatya")
        citiesList.add("manisa")
        citiesList.add("mardin")
        citiesList.add("mersin")
        citiesList.add("mugla")
        citiesList.add("mus")
        citiesList.add("nevsehir")
        citiesList.add("nigde")
        citiesList.add("ordu")
        citiesList.add("osmaniye")
        citiesList.add("rize")
        citiesList.add("samsun")
        citiesList.add("sanliurfa")
        citiesList.add("siirt")
        citiesList.add("sinop")
        citiesList.add("sivas")
        citiesList.add("sirnak")
        citiesList.add("tekirdag")
        citiesList.add("tokat")
        citiesList.add("trabzon")
        citiesList.add("tunceli")
        citiesList.add("usak")
        citiesList.add("van")
        citiesList.add("yalova")
        citiesList.add("yozgat")
        citiesList.add("zonguldak")
        citiesList.add("A Coruña")
        citiesList.add("Aachen")
        citiesList.add("Aarhus")
        citiesList.add("Abbeville")
        citiesList.add("Aberdeen (UK)")
        citiesList.add("Aberdeen (South Dakota)")
        citiesList.add("Aberdeen (Washington)")
        citiesList.add("Abidjan")
        citiesList.add("Abilene")
        citiesList.add("Abu Dhabi")
        citiesList.add("Abuja")
        citiesList.add("Acapulco")
        citiesList.add("Accra")
        citiesList.add("Adamstown")
        citiesList.add("Addis Ababa")
        citiesList.add("Adelaide")
        citiesList.add("Adelboden")
        citiesList.add("Agadir")
        citiesList.add("Agde")
        citiesList.add("Agen")
        citiesList.add("Agios Nikolaos")
        citiesList.add("Agra")
        citiesList.add("Agrigento")
        citiesList.add("Agropoli")
        citiesList.add("Ahmedabad")
        citiesList.add("Aigues-Mortes")
        citiesList.add("Aix-en-Provence")
        citiesList.add("Aix-les-Bains")
        citiesList.add("Ajaccio")
        citiesList.add("Ajman")
        citiesList.add("Akron")
        citiesList.add("Al Ain")
        citiesList.add("Alanya")
        citiesList.add("Alaró")
        citiesList.add("Albacete")
        citiesList.add("Albany")
        citiesList.add("Albenga")
        citiesList.add("Albi")
        citiesList.add("Albufeira")
        citiesList.add("Albuquerque")
        citiesList.add("Alcudia")
        citiesList.add("Aleppo")
        citiesList.add("Alessandria")
        citiesList.add("Ålesund")
        citiesList.add("Alexandria (U.S.)")
        citiesList.add("Alexandria (Egypt)")
        citiesList.add("Algeciras")
        citiesList.add("Alghero")
        citiesList.add("Algiers")
        citiesList.add("Alicante")
        citiesList.add("Alkmaar")
        citiesList.add("Allentown")
        citiesList.add("Almaty")
        citiesList.add("Alofi")
        citiesList.add("Alpe d'Huez")
        citiesList.add("Alta Badia")
        citiesList.add("Altea")
        citiesList.add("Altoona")
        citiesList.add("Amagansett")
        citiesList.add("Amalfi")
        citiesList.add("Amapala")
        citiesList.add("Amarillo")
        citiesList.add("Ambon")
        citiesList.add("Amersfoort")
        citiesList.add("Amiens")
        citiesList.add("Amman")
        citiesList.add("Amsterdam")
        citiesList.add("Anaheim")
        citiesList.add("Anchorage")
        citiesList.add("Ancona")
        citiesList.add("Andalo")
        citiesList.add("Andermatt")
        citiesList.add("Andorra la Vella")
        citiesList.add("Andratx")
        citiesList.add("Andria")
        citiesList.add("Angeles City")
        citiesList.add("Angers")
        citiesList.add("Angoulême")

        citiesList.add("Ann Arbor")
        citiesList.add("Anna Maria City")
        citiesList.add("Annapolis")
        citiesList.add("Annecy")

        citiesList.add("Antananarivo")
        citiesList.add("Antibes")
        citiesList.add("Antigua Guatemala")
        citiesList.add("Antwerp")
        citiesList.add("Anzio")
        citiesList.add("Ao Nang")
        citiesList.add("Aosta")
        citiesList.add("Apeldoorn")
        citiesList.add("Apia")
        citiesList.add("Appleton")
        citiesList.add("Aqaba")
        citiesList.add("Aracaju")
        citiesList.add("Arcachon")
        citiesList.add("Arenzano")
        citiesList.add("Arequipa")
        citiesList.add("Arezzo")
        citiesList.add("Argostoli")
        citiesList.add("Arica")
        citiesList.add("Arles")
        citiesList.add("Arlington (Virginia)")
        citiesList.add("Arlington (Texas)")
        citiesList.add("Armagh")
        citiesList.add("Arnhem")
        citiesList.add("Arosa")
        citiesList.add("Arras")
        citiesList.add("Arrecife")
        citiesList.add("Artà")
        citiesList.add("Asbury Park")
        citiesList.add("Ascoli Piceno")
        citiesList.add("Ascona")
        citiesList.add("Ashdod")
        citiesList.add("Ashgabat")
        citiesList.add("Ashkelon")
        citiesList.add("Asmara")
        citiesList.add("Aspen")
        citiesList.add("Asti")
        citiesList.add("Astoria")
        citiesList.add("Asunción")
        citiesList.add("Atafu")
        citiesList.add("Athens")
        citiesList.add("Athlone")
        citiesList.add("Atlanta")
        citiesList.add("Atlantic Beach (New York)")
        citiesList.add("Atlantic Beach (North Carolina)")
        citiesList.add("Atlantic City")
        citiesList.add("Auckland")
        citiesList.add("Augsburg")
        citiesList.add("Augusta (Georgia)")
        citiesList.add("Augusta (Maine)")
        citiesList.add("Aurora (Colorado)")
        citiesList.add("Aurora (Illinois)")
        citiesList.add("Austin")
        citiesList.add("Auxerre")
        citiesList.add("Avalon (California)")
        citiesList.add("Avalon (New Jersey)")
        citiesList.add("Avarua")
        citiesList.add("Aveiro")
        citiesList.add("Avellino")
        citiesList.add("Avignon")
        citiesList.add("Avila Beach")
        citiesList.add("Avon")
        citiesList.add("Avoriaz")
        citiesList.add("Axamer Lizum")
        citiesList.add("Ayia Napa")
        citiesList.add("Azusa")
        citiesList.add("Bad Gastein")
        citiesList.add("Bad Hofgastein")
        citiesList.add("Baden")
        citiesList.add("Baghdad")
        citiesList.add("Baiona")
        citiesList.add("Bakersfield")
        citiesList.add("Baku")
        citiesList.add("Bald Head Island")
        citiesList.add("Baltimore")
        citiesList.add("Bamako")
        citiesList.add("Banda Aceh")
        citiesList.add("Bandar Seri Begawan")
        citiesList.add("Bandol")
        citiesList.add("Banff")
        citiesList.add("Bangalore")
        citiesList.add("Bangkok")
        citiesList.add("Bangor")
        citiesList.add("Bangui")
        citiesList.add("Banjul")
        citiesList.add("Bar")
        citiesList.add("Bar Harbor")
        citiesList.add("Barcelona")
        citiesList.add("Bari")
        citiesList.add("Barletta")
        citiesList.add("Barnegat Light")
        citiesList.add("Barnum Island")
        citiesList.add("Barrie")
        citiesList.add("Barstow")
        citiesList.add("Basel")
        citiesList.add("Basey")
        citiesList.add("Basseterre")
        citiesList.add("Basse-Terre")
        citiesList.add("Bastia")
        citiesList.add("Bata")
        citiesList.add("Batam")
        citiesList.add("Bath")
        citiesList.add("Baton Rouge")
        citiesList.add("Batu")
        citiesList.add("Batumi")
        citiesList.add("Bayonne")
        citiesList.add("Beach Haven")
        citiesList.add("Bear Island")
        citiesList.add("Beaufort")
        citiesList.add("Beaulieu-sur-Mer")
        citiesList.add("Beaumont")
        citiesList.add("Beaune")
        citiesList.add("Beersheba")
        citiesList.add("Beijing")
        citiesList.add("Beirut")
        citiesList.add("Belek")
        citiesList.add("Belfast")
        citiesList.add("Belfort")
        citiesList.add("Belgrade")
        citiesList.add("Belize City")
        citiesList.add("Bellingham")
        citiesList.add("Bellinzona")
        citiesList.add("Belluno")
        citiesList.add("Belmopan")
        citiesList.add("Belo Horizonte")
        citiesList.add("Bemidji")
        citiesList.add("Benalmadena")
        citiesList.add("Bend")
        citiesList.add("Bendigo")
        citiesList.add("Benevento")
        citiesList.add("Benicàssim")
        citiesList.add("Benidorm")
        citiesList.add("Bergamo")
        citiesList.add("Bergen")
        citiesList.add("Bergerac")
        citiesList.add("Berkeley")
        citiesList.add("Berlin")
        citiesList.add("Bern")
        citiesList.add("Besançon")
        citiesList.add("Bethlehem")
        citiesList.add("Beverly Hills")
        citiesList.add("Béziers")
        citiesList.add("Biarritz")
        citiesList.add("Biel/Bienne")
        citiesList.add("Bielefeld")
        citiesList.add("Biella")
        citiesList.add("Big Pine Key")
        citiesList.add("Bilbao")
        citiesList.add("Billings")
        citiesList.add("Biloxi")
        citiesList.add("Birmingham (UK)")
        citiesList.add("Birmingham (U.S.)")
        citiesList.add("Bishkek")
        citiesList.add("Bismarck")
        citiesList.add("Bissau")
        citiesList.add("Blanes")
        citiesList.add("Bled")
        citiesList.add("Blois")
        citiesList.add("Bloomington")
        citiesList.add("Blumenau")
        citiesList.add("Boca Chica")
        citiesList.add("Boca Grande")
        citiesList.add("Boca Raton")
        citiesList.add("Bochum")
        citiesList.add("Bodrum")
        citiesList.add("Bogotá")
        citiesList.add("Boise")
        citiesList.add("Bologna")
        citiesList.add("Bolzano")
        citiesList.add("Bonifacio")
        citiesList.add("Bonn")
        citiesList.add("Bordeaux")
        citiesList.add("Bordighera")
        citiesList.add("Bormio")
        citiesList.add("Boston")
        citiesList.add("Boulder")
        citiesList.add("Boulogne-sur-Mer")
        citiesList.add("Bourges")
        citiesList.add("Bowling Green")
        citiesList.add("Boynton Beach")
        citiesList.add("Bozeman")
        citiesList.add("Bradenton")
        citiesList.add("Bradenton Beach")
        citiesList.add("Bradford")
        citiesList.add("Braga")
        citiesList.add("Brampton")
        citiesList.add("Brandon")
        citiesList.add("Brantford")
        citiesList.add("Brasilia")
        citiesList.add("Bratislava")
        citiesList.add("Braunschweig")
        citiesList.add("Brazzaville")
        citiesList.add("Breda")
        citiesList.add("Bregenz")
        citiesList.add("Brela")
        citiesList.add("Bremen")
        citiesList.add("Bremerhaven")
        citiesList.add("Brescia")
        citiesList.add("Brest")
        citiesList.add("Briançon")
        citiesList.add("Bridgehampton")
        citiesList.add("Bridgeport")
        citiesList.add("Bridgetown")
        citiesList.add("Brigantine")
        citiesList.add("Brighton")
        citiesList.add("Brindisi")
        citiesList.add("Brisbane")
        citiesList.add("Bristol")
        citiesList.add("Brixen")
        citiesList.add("Brixental")
        citiesList.add("Brno")
        citiesList.add("Brookings")
        citiesList.add("Brownsville")
        citiesList.add("Bruges")
        citiesList.add("Brunswick")
        citiesList.add("Brussels")
        citiesList.add("Bucharest")
        citiesList.add("Budapest")
        citiesList.add("Budva")
        citiesList.add("Buenos Aires")
        citiesList.add("Buffalo")
        citiesList.add("Bujumbura")
        citiesList.add("Bukittinggi")
        citiesList.add("Burgas")
        citiesList.add("Burlington (U.S.)")
        citiesList.add("Burlington (Canada)")
        citiesList.add("Burnt Pine")
        citiesList.add("Burton")
        citiesList.add("Butte")
        citiesList.add("Buxton")
        citiesList.add("Cabo San Lucas")
        citiesList.add("Cadaqués")
        citiesList.add("Cádiz")
        citiesList.add("Caen")
        citiesList.add("Cagliari")
        citiesList.add("Cagnes-sur-Mer")
        citiesList.add("Cairns")
        citiesList.add("Cairo")
        citiesList.add("Cala Bona")
        citiesList.add("Cala d'Or")
        citiesList.add("Cala Millor")
        citiesList.add("Cala Ratjada")
        citiesList.add("Calais")
        citiesList.add("Calella")
        citiesList.add("Calgary")
        citiesList.add("Cali")
        citiesList.add("Caloundra")
        citiesList.add("Calp")
        citiesList.add("Caltanissetta")
        citiesList.add("Calvi")
        citiesList.add("Cambridge (UK)")
        citiesList.add("Cambridge (U.S.)")
        citiesList.add("Cambrils")
        citiesList.add("Camden")
        citiesList.add("Campbell River")
        citiesList.add("Campinas")
        citiesList.add("Campobasso")
        citiesList.add("Can Pastilla")
        citiesList.add("Can Picafort")
        citiesList.add("Canazei")
        citiesList.add("Canberra")
        citiesList.add("Cancun")
        citiesList.add("Cannes")
        citiesList.add("Cannon Beach")
        citiesList.add("Canterbury")
        citiesList.add("Canton")
        citiesList.add("Canyamel")
        citiesList.add("Capdepera")
        citiesList.add("Cape Canaveral")
        citiesList.add("Cape Coral")
        citiesList.add("Cape May")
        citiesList.add("Cape Town")
        citiesList.add("Capitola")
        citiesList.add("Captiva")
        citiesList.add("Caracas")
        citiesList.add("Carbonia")
        citiesList.add("Carcassonne")
        citiesList.add("Cardiff")
        citiesList.add("Carlisle")
        citiesList.add("Carlsbad")
        citiesList.add("Carmel-by-the-Sea")
        citiesList.add("Carolina Beach")
        citiesList.add("Carova Beach")
        citiesList.add("Carpi")
        citiesList.add("Carpinteria")
        citiesList.add("Carrara")
        citiesList.add("Carson City")
        citiesList.add("Cartagena (Colombia)")
        citiesList.add("Cartagena (Spain)")
        citiesList.add("Casablanca")
        citiesList.add("Caserta")
        citiesList.add("Casper")
        citiesList.add("Cassis")
        citiesList.add("Castellón de la Plana")
        citiesList.add("Castelrotto")
        citiesList.add("Castletown")
        citiesList.add("Castries")
        citiesList.add("Caswell Beach")
        citiesList.add("Catania")
        citiesList.add("Catanzaro")
        citiesList.add("Caxias do Sul")
        citiesList.add("Cayenne")
        citiesList.add("Cebu City")
        citiesList.add("Cedar Island")
        citiesList.add("Cedar Key")
        citiesList.add("Cedar Rapids")
        citiesList.add("Celle")
        citiesList.add("Cervinia")
        citiesList.add("Cesena")
        citiesList.add("Český Krumlov")
        citiesList.add("Çeşme")
        citiesList.add("Chamonix")
        citiesList.add("Chandler")
        citiesList.add("Chania")
        citiesList.add("Charleroi")
        citiesList.add("Charleston (West Virginia)")
        citiesList.add("Charleston (South Carolina)")
        citiesList.add("Charlestown")
        citiesList.add("Charlotte")
        citiesList.add("Charlotte Amalie")
        citiesList.add("Charlottetown")
        citiesList.add("Chartres")
        citiesList.add("Chatham")
        citiesList.add("Chattanooga")
        citiesList.add("Chelmsford")
        citiesList.add("Chemnitz")
        citiesList.add("Chennai")
        citiesList.add("Cherbourg")
        citiesList.add("Chesapeake")
        citiesList.add("Chester")
        citiesList.add("Cheyenne")
        citiesList.add("Chiang Mai")
        citiesList.add("Chiang Rai")
        citiesList.add("Chiavari")
        citiesList.add("Chicago")
        citiesList.add("Chichester")
        citiesList.add("Chiclayo")
        citiesList.add("Chieti")
        citiesList.add("Chincoteague")
        citiesList.add("Chioggia")
        citiesList.add("Chios")
        citiesList.add("Chișinău")
        citiesList.add("Chokoloskee")
        citiesList.add("Chonburi")
        citiesList.add("Christchurch")
        citiesList.add("Christiansted")
        citiesList.add("Chula Vista")
        citiesList.add("Chur")
        citiesList.add("Cincinnati")
        citiesList.add("Ciutadella de Menorca")
        citiesList.add("Civitavecchia")
        citiesList.add("Clarksville")
        citiesList.add("Clearwater")
        citiesList.add("Clearwater Beach")
        citiesList.add("Clermont-Ferrand")
        citiesList.add("Cleveland")
        citiesList.add("Cockburn Town")
        citiesList.add("Cocoa Beach")
        citiesList.add("Coconut Creek")
        citiesList.add("Coimbra")
        citiesList.add("Collioure")
        citiesList.add("Colmar")
        citiesList.add("Cologne")
        citiesList.add("Colombo")
        citiesList.add("Colón")
        citiesList.add("Colonia del Sacramento")
        citiesList.add("Colorado Springs")
        citiesList.add("Columbia (South Carolina)")
        citiesList.add("Columbia (Missouri)")
        citiesList.add("Columbus")
        citiesList.add("Como")
        citiesList.add("Conakry")
        citiesList.add("Concepción")
        citiesList.add("Concord")
        citiesList.add("Conil de la Frontera")
        citiesList.add("Conway")
        citiesList.add("Copenhagen")
        citiesList.add("Coral Springs")
        citiesList.add("Córdoba (Argentina)")
        citiesList.add("Córdoba (Spain)")
        citiesList.add("Corfu")
        citiesList.add("Corinth")
        citiesList.add("Cork")
        citiesList.add("Coro")
        citiesList.add("Corolla")
        citiesList.add("Coron Town")
        citiesList.add("Corpus Christi")
        citiesList.add("Corralejo")
        citiesList.add("Cortina d'Ampezzo")
        citiesList.add("Cosenza")
        citiesList.add("Costa Adeje")
        citiesList.add("Cotabato City")
        citiesList.add("Cottbus")
        citiesList.add("Courchevel")
        citiesList.add("Courmayeur")
        citiesList.add("Courtenay")
        citiesList.add("Coventry")
        citiesList.add("Covington")
        citiesList.add("Coxen Hole")
        citiesList.add("Coyhaique")
        citiesList.add("Cozumel")
        citiesList.add("Crans-Montana")
        citiesList.add("Cremona")
        citiesList.add("Crotone")
        citiesList.add("Cruz Bay")
        citiesList.add("Cudjoe Key")
        citiesList.add("Cuenca (Ecuador)")
        citiesList.add("Cuenca (Spain)")
        citiesList.add("Cumaná")
        citiesList.add("Cuneo")
        citiesList.add("Cusco")
        citiesList.add("Da Nang")
        citiesList.add("Dachau")
        citiesList.add("Dahab")
        citiesList.add("Dakar")
        citiesList.add("Dallas")
        citiesList.add("Damascus")
        citiesList.add("Dana Point")
        citiesList.add("Dar es Salaam")
        citiesList.add("Darien")
        citiesList.add("Darmstadt")
        citiesList.add("Darwin")
        citiesList.add("Daufuskie Island")
        citiesList.add("Daugavpils")
        citiesList.add("Dauphin Island")
        citiesList.add("Davao City")
        citiesList.add("Davenport")
        citiesList.add("Davos")
        citiesList.add("Dayton")
        citiesList.add("Daytona Beach")
        citiesList.add("Deauville")
        citiesList.add("Decatur")
        citiesList.add("Deerfield Beach")
        citiesList.add("Del Mar")
        citiesList.add("Delft")
        citiesList.add("Delhi")
        citiesList.add("Delray Beach")
        citiesList.add("Den Bosch")
        citiesList.add("Denia")
        citiesList.add("Denpasar")
        citiesList.add("Denton")
        citiesList.add("Denver")
        citiesList.add("Derby")
        citiesList.add("Derry")
        citiesList.add("Des Moines")
        citiesList.add("Detroit")
        citiesList.add("Dewees Island")
        citiesList.add("Dhaka")
        citiesList.add("Diamond Beach")
        citiesList.add("Didim")
        citiesList.add("Dieppe")
        citiesList.add("Dijon")
        citiesList.add("Dili")
        citiesList.add("Djibouti")
        citiesList.add("Dodoma")
        citiesList.add("Doha")
        citiesList.add("Dolomiti Superski")
        citiesList.add("Dordrecht")
        citiesList.add("Dorfgastein")
        citiesList.add("Dortmund")
        citiesList.add("Dothan")
        citiesList.add("Douala")
        citiesList.add("Douglas")
        citiesList.add("Dover (Delaware)")
        citiesList.add("Dover (New Hampshire)")
        citiesList.add("Dresden")
        citiesList.add("Dubai")
        citiesList.add("Dublin")
        citiesList.add("Dubrovnik")
        citiesList.add("Duck")
        citiesList.add("Duisburg")
        citiesList.add("Duluth")
        citiesList.add("Dumaguete")
        citiesList.add("Dumai")
        citiesList.add("Duncan")
        citiesList.add("Dundalk")
        citiesList.add("Dundee")
        citiesList.add("Dunedin")
        citiesList.add("Dunkirk")
        citiesList.add("Durham (UK)")
        citiesList.add("Durham (U.S.)")
        citiesList.add("Dushanbe")
        citiesList.add("Düsseldorf")
        citiesList.add("East Atlantic Beach")
        citiesList.add("East Hampton")
        citiesList.add("Eastbourne")
        citiesList.add("Eastport")
        citiesList.add("Eatons Neck")
        citiesList.add("Eau Claire")
        citiesList.add("Edgartown")
        citiesList.add("Edinburgh")
        citiesList.add("Edisto Beach")
        citiesList.add("Edmonton")
        citiesList.add("Eilat")
        citiesList.add("Eindhoven")
        citiesList.add("El Nido")
        citiesList.add("El Paso")
        citiesList.add("Elche")
        citiesList.add("Elizabeth")
        citiesList.add("Elko")
        citiesList.add("Ellmau")
        citiesList.add("Elm")
        citiesList.add("Emerald Isle")
        citiesList.add("Empuriabrava")
        citiesList.add("Encinitas")
        citiesList.add("Engelberg")
        citiesList.add("Englewood Beach")
        citiesList.add("Enna")
        citiesList.add("Enschede")
        citiesList.add("Épinal")
        citiesList.add("Erfurt")
        citiesList.add("Erie")
        citiesList.add("Erlangen")
        citiesList.add("Esbjerg")
        citiesList.add("Espace Killy")
        citiesList.add("Essaouira")
        citiesList.add("Essen")
        citiesList.add("Estepona")
        citiesList.add("Étretat")
        citiesList.add("Eugene")
        citiesList.add("Eureka")
        citiesList.add("Evansville")
        citiesList.add("Everett")
        citiesList.add("Everglades City")
        citiesList.add("Exeter")
        citiesList.add("Èze")
        citiesList.add("Faenza")
        citiesList.add("Fairbanks")
        citiesList.add("Fakaofo")
        citiesList.add("Falmouth")
        citiesList.add("Famagusta")
        citiesList.add("Fano")
        citiesList.add("Fargo")
        citiesList.add("Faro")
        citiesList.add("Fayetteville (North Carolina)")
        citiesList.add("Fayetteville (Arkansas)")
        citiesList.add("Fermo")
        citiesList.add("Fernandina Beach")
        citiesList.add("Ferrara")
        citiesList.add("Fethiye")
        citiesList.add("Fez")
        citiesList.add("Fieberbrunn")
        citiesList.add("Figure Eight Island")
        citiesList.add("Filzmoos")
        citiesList.add("Finale Ligure")
        citiesList.add("Fisher Island")
        citiesList.add("Fiumicino")
        citiesList.add("Flagstaff")
        citiesList.add("Flaine")
        citiesList.add("Flint")
        citiesList.add("Florence")
        citiesList.add("Florence (Alabama)")
        citiesList.add("Flores")
        citiesList.add("Foggia")
        citiesList.add("Folgarida")
        citiesList.add("Folly Beach")
        citiesList.add("Fontana")
        citiesList.add("Forest Beach")
        citiesList.add("Forlì")
        citiesList.add("Fort Caswell")
        citiesList.add("Fort Collins")
        citiesList.add("Fort Fremont")
        citiesList.add("Fort Lauderdale")
        citiesList.add("Fort Myers")
        citiesList.add("Fort Myers Beach")
        citiesList.add("Fort Pierce")
        citiesList.add("Fort Smith")
        citiesList.add("Fort Wayne")
        citiesList.add("Fort Worth")
        citiesList.add("Fort-de-France")
        citiesList.add("Forte dei Marmi")
        citiesList.add("Foz do Iguaçu")
        citiesList.add("Frankfort")
        citiesList.add("Frankfurt am Main")
        citiesList.add("Franklin")
        citiesList.add("Frederick")
        citiesList.add("Fredericton")
        citiesList.add("Frederiksted")
        citiesList.add("Freeport")
        citiesList.add("Freetown")
        citiesList.add("Freiburg")
        citiesList.add("Fremont")
        citiesList.add("Fresno")
        citiesList.add("Fribourg")
        citiesList.add("Fripp Island")
        citiesList.add("Frisco")
        citiesList.add("Frogmore")
        citiesList.add("Frosinone")
        citiesList.add("Fuengirola")
        citiesList.add("Fujairah")
        citiesList.add("Fukuoka")
        citiesList.add("Funafuti")
        citiesList.add("Funchal")
        citiesList.add("Gaborone")
        citiesList.add("Gainesville")
        citiesList.add("Galtür")
        citiesList.add("Galway")
        citiesList.add("Gandia")
        citiesList.add("Garden Grove")
        citiesList.add("Garland")
        citiesList.add("Gastonia")
        citiesList.add("Gatineau")
        citiesList.add("Gaza City")
        citiesList.add("Gdansk")
        citiesList.add("Gdynia")
        citiesList.add("Geelong")
        citiesList.add("Gelsenkirchen")
        citiesList.add("Geneva")
        citiesList.add("Genoa")
        citiesList.add("George Town (Cayman Islands)")
        citiesList.add("George Town (Malaysia)")
        citiesList.add("Georgetown")
        citiesList.add("Ghent")
        citiesList.add("Gijón")
        citiesList.add("Gilbert")
        citiesList.add("Girona")
        citiesList.add("Gitega")
        citiesList.add("Giza")
        citiesList.add("Glasgow")
        citiesList.add("Glendale (Arizona)")
        citiesList.add("Glendale (California)")
        citiesList.add("Gloucester")
        citiesList.add("Gold Coast")
        citiesList.add("Gorizia")
        citiesList.add("Gosau")
        citiesList.add("Gothenburg")
        citiesList.add("Göttingen")
        citiesList.add("Gouda")
        citiesList.add("Granada (Spain)")
        citiesList.add("Granada (Nicaragua)")
        citiesList.add("Grand Forks")
        citiesList.add("Grand Island (Nebraska)")
        citiesList.add("Grand Island (New York)")
        citiesList.add("Grand Junction")
        citiesList.add("Grand Prairie")
        citiesList.add("Grand Rapids")
        citiesList.add("Grande Prairie")
        citiesList.add("Granville")
        citiesList.add("Grasse")
        citiesList.add("Graz")
        citiesList.add("Great Falls")
        citiesList.add("Greeley")
        citiesList.add("Green Bay")
        citiesList.add("Greensboro")
        citiesList.add("Greenville NC")
        citiesList.add("Greenville SC")
        citiesList.add("Grenoble")
        citiesList.add("Grindelwald")
        citiesList.add("Groningen")
        citiesList.add("Grossarl")
        citiesList.add("Grosseto")
        citiesList.add("Grover Beach")
        citiesList.add("Gstaad")
        citiesList.add("Guadalajara")
        citiesList.add("Guadalupe")
        citiesList.add("Guangzhou")
        citiesList.add("Guatemala City")
        citiesList.add("Guayaquil")
        citiesList.add("Guelph")
        citiesList.add("Guimarães")
        citiesList.add("Gulf Shores")
        citiesList.add("Gulfport")
        citiesList.add("Gustavia")
        citiesList.add("Haarlem")
        citiesList.add("Haifa")
        citiesList.add("Half Moon Bay")
        citiesList.add("Halifax")
        citiesList.add("Halle")
        citiesList.add("Hamburg")
        citiesList.add("Hamilton (Bermuda)")
        citiesList.add("Hamilton (Canada)")
        citiesList.add("Hamilton (New Zealand)")
        citiesList.add("Hampton")
        citiesList.add("Hampton Bays")
        citiesList.add("Hanford")
        citiesList.add("Hangzhou")
        citiesList.add("Hannover")
        citiesList.add("Hanoi")
        citiesList.add("Harare")
        citiesList.add("Harbor Island")
        citiesList.add("Harbor Isle")
        citiesList.add("Harbour Town")
        citiesList.add("Hargeisa")
        citiesList.add("Harkers Island")
        citiesList.add("Harrisburg")
        citiesList.add("Hartford")
        citiesList.add("Harvey Cedars")
        citiesList.add("Hasselt")
        citiesList.add("Hastings")
        citiesList.add("Hat Yai")
        citiesList.add("Hatteras")
        citiesList.add("Hattiesburg")
        citiesList.add("Havana")
        citiesList.add("Heidelberg")
        citiesList.add("Heilbronn")
        citiesList.add("Heiligenblut")
        citiesList.add("Helena")
        citiesList.add("Helsinki")
        citiesList.add("Henderson")
        citiesList.add("Heraklion")
        citiesList.add("Herceg Novi")
        citiesList.add("Hereford")
        citiesList.add("Hermosa Beach")
        citiesList.add("Hervey Bay")
        citiesList.add("Hialeah")
        citiesList.add("Hillsboro")
        citiesList.add("Hilton Head Island")
        citiesList.add("Hilton Head Plantation")
        citiesList.add("Hinterglemm")
        citiesList.add("Hinterstoder")
        citiesList.add("Hiroshima")
        citiesList.add("Hoi An")
        citiesList.add("Hobart")
        citiesList.add("Ho Chi Minh City")
        citiesList.add("Holbrook")
        citiesList.add("Holden Beach")
        citiesList.add("Hollywood (Florida)")
        citiesList.add("Holmes Beach")
        citiesList.add("Honfleur")
        citiesList.add("Hong Kong")
        citiesList.add("Honiara")
        citiesList.add("Honolulu")
        citiesList.add("Horsens")
        citiesList.add("Hot Springs")
        citiesList.add("Houston")
        citiesList.add("Hua Hin")
        citiesList.add("Hue")
        citiesList.add("Hunting Island")
        citiesList.add("Huntington")
        citiesList.add("Huntington Beach")
        citiesList.add("Huntsville")
        citiesList.add("Hurghada")
        citiesList.add("Hvar")
        citiesList.add("Hyères")
        citiesList.add("Ibiza Town")
        citiesList.add("Iloilo City")
        citiesList.add("Imola")
        citiesList.add("Imperia")
        citiesList.add("Inca")
        citiesList.add("Indian Beach")
        citiesList.add("Indianapolis")
        citiesList.add("Ingolstadt")
        citiesList.add("Innsbruck")
        citiesList.add("Interlaken")
        citiesList.add("Inverness")
        citiesList.add("Ioannina")
        citiesList.add("Iqaluit")
        citiesList.add("Iquitos")
        citiesList.add("Irvine")
        citiesList.add("Irving")
        citiesList.add("Ischgl")
        citiesList.add("Isernia")
        citiesList.add("Lahore")
        citiesList.add("Islamorada")
        citiesList.add("Island Park")
        citiesList.add("Isle of Palms")
        citiesList.add("Izola")
        citiesList.add("Jackson")
        citiesList.add("Jackson (Tennessee)")
        citiesList.add("Jacksonville")
        citiesList.add("Jaipur")
        citiesList.add("Jakarta")
        citiesList.add("Jefferson City")
        citiesList.add("Jekyll Island")
        citiesList.add("Jena")
        citiesList.add("Jerez de la Frontera")
        citiesList.add("Jersey City")
        citiesList.add("Jerusalem")
        citiesList.add("Johannesburg")
        citiesList.add("Johns Island")
        citiesList.add("Johnson City")
        citiesList.add("Joinville")
        citiesList.add("Jonesboro")
        citiesList.add("Juan Griego")
        citiesList.add("Juan-les-Pins")
        citiesList.add("Juba")
        citiesList.add("Juiz de Fora")
        citiesList.add("Juneau")
        citiesList.add("Jungfrau")
        citiesList.add("Jupiter")
        citiesList.add("Jupiter Island")
        citiesList.add("Jūrmala")
        citiesList.add("Kabul")
        citiesList.add("Kaiserslautern")
        citiesList.add("Kalamata")
        citiesList.add("Kalamazoo")
        citiesList.add("Kamloops")
        citiesList.add("Kampala")
        citiesList.add("Kanchanaburi")
        citiesList.add("Kansas City")
        citiesList.add("Kansas City (Kansas)")
        citiesList.add("Kappl")
        citiesList.add("Kaprun")
        citiesList.add("Islamabad")
        citiesList.add("Karlovy Vary")
        citiesList.add("Karlsruhe")
        citiesList.add("Kassel")
        citiesList.add("Kastoria")
        citiesList.add("Kathmandu")
        citiesList.add("Kaunas")
        citiesList.add("Kavala")
        citiesList.add("Kearney")
        citiesList.add("Keene")
        citiesList.add("Kelowna")
        citiesList.add("Kemer")
        citiesList.add("Kenosha")
        citiesList.add("Key Biscayne")
        citiesList.add("Key Largo")
        citiesList.add("Key West")
        citiesList.add("Khao Lak")
        citiesList.add("Khartoum")
        citiesList.add("Kiawah Island")
        citiesList.add("Kiel")
        citiesList.add("Kigali")
        citiesList.add("Kilkenny")
        citiesList.add("Kill Devil Hills")
        citiesList.add("Kingman")
        citiesList.add("Kingston (Jamaica)")
        citiesList.add("Kingston (Norfolk Island)")
        citiesList.add("Kingston (Canada)")
        citiesList.add("Kingston upon Hull")
        citiesList.add("Kingstown")
        citiesList.add("Kinshasa")
        citiesList.add("Kissimmee")
        citiesList.add("Kitchener")
        citiesList.add("Kitty Hawk")
        citiesList.add("Kitzbühel")
        citiesList.add("Klagenfurt")
        citiesList.add("Klaipėda")
        citiesList.add("Knotts Island")
        citiesList.add("Knoxville")
        citiesList.add("Kobe")
        citiesList.add("Koblenz")
        citiesList.add("Kolding")
        citiesList.add("Kolkata")
        citiesList.add("Komotini")
        citiesList.add("Koper")
        citiesList.add("Koror")
        citiesList.add("Kos")
        citiesList.add("Košice")
        citiesList.add("Kotor")
        citiesList.add("Krabi")
        citiesList.add("Krakow")
        citiesList.add("Kralendijk")
        citiesList.add("Krefeld")
        citiesList.add("Kuah")
        citiesList.add("Kuala Lumpur")
        citiesList.add("Kure Beach")
        citiesList.add("Kuşadası")
        citiesList.add("Kuta")
        citiesList.add("Kutná Hora")
        citiesList.add("Kuwait City")
        citiesList.add("Kyiv")
        citiesList.add("Kyoto")
        citiesList.add("Kyrenia")
        citiesList.add("La Ceiba")
        citiesList.add("La Ciotat")
        citiesList.add("La Clusaz")
        citiesList.add("La Laguna")
        citiesList.add("La Maddalena")
        citiesList.add("La Manga")
        citiesList.add("La Paz")
        citiesList.add("La Plagne")
        citiesList.add("La Plata")
        citiesList.add("La Rochelle")
        citiesList.add("La Romana")
        citiesList.add("La Serena")
        citiesList.add("La Seyne-sur-Mer")
        citiesList.add("La Spezia")
        citiesList.add("La Thuile")
        citiesList.add("Laax")
        citiesList.add("Labasa")
        citiesList.add("Labrador City")
        citiesList.add("Labuan Bajo")
        citiesList.add("Lady's Island")
        citiesList.add("Ladysmith")
        citiesList.add("Lafayette (Indiana)")
        citiesList.add("Lafayette (Louisiana)")
        citiesList.add("Lagos (Nigeria)")
        citiesList.add("Lagos (Portugal)")
        citiesList.add("Laguna Beach")
        citiesList.add("Karachi")
        citiesList.add("Lakeland")
        citiesList.add("Lalitpur")
        citiesList.add("Lamezia Terme")
        citiesList.add("Lancaster")
        citiesList.add("Lancaster (U.S.)")
        citiesList.add("Landshut")
        citiesList.add("Lansing")
        citiesList.add("L'Aquila")
        citiesList.add("Laredo")
        citiesList.add("Largo")
        citiesList.add("Larnaca")
        citiesList.add("Las Cruces")
        citiesList.add("Las Palmas")
        citiesList.add("Las Vegas")
        citiesList.add("Latina")
        citiesList.add("Laurel Bay")
        citiesList.add("Lausanne")
        citiesList.add("Lautoka")
        citiesList.add("Laval")
        citiesList.add("Lawton")
        citiesList.add("Layton")
        citiesList.add("Le Havre")
        citiesList.add("Le Lavandou")
        citiesList.add("Le Mans")
        citiesList.add("Le Puy-en-Velay")
        citiesList.add("Lecce")
        citiesList.add("Lecco")
        citiesList.add("Lech")
        citiesList.add("Leeds")
        citiesList.add("Legian")
        citiesList.add("Legnano")
        citiesList.add("Leicester")
        citiesList.add("Leiden")
        citiesList.add("Leipzig")
        citiesList.add("Lemgo")
        citiesList.add("Leogang")
        citiesList.add("León")
        citiesList.add("Les Arcs")
        citiesList.add("Les Deux Alpes")
        citiesList.add("Les Gets")
        citiesList.add("Les Houches")
        citiesList.add("Les Menuires")
        citiesList.add("Lethbridge")
        citiesList.add("Leuven")
        citiesList.add("Leverkusen")
        citiesList.add("Lexington")
        citiesList.add("Liberec")
        citiesList.add("Libreville")
        citiesList.add("Lichfield")
        citiesList.add("Lido Beach")
        citiesList.add("Lido Key")
        citiesList.add("Liège")
        citiesList.add("Lienz")
        citiesList.add("Liepāja")
        citiesList.add("Lille")
        citiesList.add("Lilongwe")
        citiesList.add("Lima")
        citiesList.add("Limassol")
        citiesList.add("Limerick")
        citiesList.add("Limoges")
        citiesList.add("Lincoln")
        citiesList.add("Lincoln")
        citiesList.add("Lindos")
        citiesList.add("Linz")
        citiesList.add("Lisbon")
        citiesList.add("Lisburn")
        citiesList.add("Little Rock")
        citiesList.add("Liverpool")
        citiesList.add("Livigno")
        citiesList.add("Livorno")
        citiesList.add("Ljubljana")
        citiesList.add("Lloret de Mar")
        citiesList.add("Llucmajor")
        citiesList.add("Loano")
        citiesList.add("Locarno")
        citiesList.add("Lodi")
        citiesList.add("Lodz")
        citiesList.add("Logan")
        citiesList.add("Logroño")
        citiesList.add("Lomé")
        citiesList.add("London (Canada)")
        citiesList.add("London")
        citiesList.add("Londrina")
        citiesList.add("Long Beach")
        citiesList.add("Long Beach (New York)")
        citiesList.add("Long Branch")
        citiesList.add("Longboat Key")
        citiesList.add("Longport")
        citiesList.add("Longview (Texas)")
        citiesList.add("Longview (Washington)")
        citiesList.add("Lorain")
        citiesList.add("Los Alamos")
        citiesList.add("Los Angeles")
        citiesList.add("Los Cabos")
        citiesList.add("Los Cristianos")
        citiesList.add("Louisville")
        citiesList.add("Lourdes")
        citiesList.add("Loutraki")
        citiesList.add("Louvain-la-Neuve")
        citiesList.add("Lowell")
        citiesList.add("Luanda")
        citiesList.add("Lubbock")
        citiesList.add("Lübeck")
        citiesList.add("Lublin")
        citiesList.add("Lucca")
        citiesList.add("Lucerne")
        citiesList.add("Lugano")
        citiesList.add("Luganville")
        citiesList.add("Lund")
        citiesList.add("Lusaka")
        citiesList.add("Luxembourg")
        citiesList.add("Luxor")
        citiesList.add("Lyon")
        citiesList.add("Maastricht")
        citiesList.add("Macerata")
        citiesList.add("Machu Picchu")
        citiesList.add("Macon")
        citiesList.add("Madera")
        citiesList.add("Madison")
        citiesList.add("Madonna di Campiglio")
        citiesList.add("Madrid")
        citiesList.add("Magaluf")
        citiesList.add("Magdeburg")
        citiesList.add("Mahón")
        citiesList.add("Mainz")
        citiesList.add("Majuro")
        citiesList.add("Makarska")
        citiesList.add("Malabo")
        citiesList.add("Malaga")
        citiesList.add("Malang")
        citiesList.add("Maldonado")
        citiesList.add("Malé")
        citiesList.add("Malia")
        citiesList.add("Malibu")
        citiesList.add("Malmö")
        citiesList.add("Manacor")
        citiesList.add("Manado")
        citiesList.add("Managua")
        citiesList.add("Manama")
        citiesList.add("Manchester (UK)")
        citiesList.add("Manchester (U.S.)")
        citiesList.add("Máncora")
        citiesList.add("Mandalika")
        citiesList.add("Manhattan Beach")
        citiesList.add("Manhattan, KS")
        citiesList.add("Manila")
        citiesList.add("Mannheim")
        citiesList.add("Manosque")
        citiesList.add("Manteo")
        citiesList.add("Mantua")
        citiesList.add("Maputo")
        citiesList.add("Mar del Plata")
        citiesList.add("Maracaibo")
        citiesList.add("Marathon")
        citiesList.add("Marbella")
        citiesList.add("Marco Island")
        citiesList.add("Margate City")
        citiesList.add("Maria Alm")
        citiesList.add("Maribor")
        citiesList.add("Marigot")
        citiesList.add("Markham")
        citiesList.add("Marmaris")
        citiesList.add("Maroochydore")
        citiesList.add("Marquette")
        citiesList.add("Marrakesh")
        citiesList.add("Marsa Alam")
        citiesList.add("Marsala")
        citiesList.add("Marseille")
        citiesList.add("Martigues")
        citiesList.add("Masaya")
        citiesList.add("Maseru")
        citiesList.add("Maspalomas")
        citiesList.add("Massa")
        citiesList.add("Mataram")
        citiesList.add("Matera")
        citiesList.add("Mayrhofen")
        citiesList.add("Mazara del Vallo")
        citiesList.add("Mbabane")
        citiesList.add("McKinney")
        citiesList.add("Mechelen")
        citiesList.add("Medan")
        citiesList.add("Medellín")
        citiesList.add("Medford")
        citiesList.add("Megève")
        citiesList.add("Melbourne (Australia)")
        citiesList.add("Melbourne (U.S.)")
        citiesList.add("Memphis")
        citiesList.add("Menton")
        citiesList.add("Merano")
        citiesList.add("Merced")
        citiesList.add("Meribel")
        citiesList.add("Mérida (Spain)")
        citiesList.add("Mérida (Venezuela)")
        citiesList.add("Meridian")
        citiesList.add("Merritt Island")
        citiesList.add("Mesa")
        citiesList.add("Messina")
        citiesList.add("Mestre")
        citiesList.add("Metz")
        citiesList.add("Mexico City")
        citiesList.add("Miami")
        citiesList.add("Middelburg")
        citiesList.add("Midland")
        citiesList.add("Mijas")
        citiesList.add("Milan")
        citiesList.add("Milford")
        citiesList.add("Millau")
        citiesList.add("Milwaukee")
        citiesList.add("Mindelo")
        citiesList.add("Minneapolis")
        citiesList.add("Minot")
        citiesList.add("Minsk")
        citiesList.add("Miramar")
        citiesList.add("Mishawaka")
        citiesList.add("Mississauga")
        citiesList.add("Missoula")
        citiesList.add("Moab")
        citiesList.add("Mobile")
        citiesList.add("Modena")
        citiesList.add("Modesto")
        citiesList.add("Modica")
        citiesList.add("Moena")
        citiesList.add("Mogadishu")
        citiesList.add("Mogi das Cruzes")
        citiesList.add("Mombasa")
        citiesList.add("Monaco City")
        citiesList.add("Mönchengladbach")
        citiesList.add("Moncton")
        citiesList.add("Monrovia (Liberia)")
        citiesList.add("Monrovia (U.S.)")
        citiesList.add("Mons")
        citiesList.add("Monschau")
        citiesList.add("Montauk")
        citiesList.add("Monte Carlo")
        citiesList.add("Monte Rosa")
        citiesList.add("Montego Bay")
        citiesList.add("Montepulciano")
        citiesList.add("Monterey")
        citiesList.add("Montevideo")
        citiesList.add("Montgomery")
        citiesList.add("Montluçon")
        citiesList.add("Montpelier")
        citiesList.add("Montpellier")
        citiesList.add("Montreal")
        citiesList.add("Montreux")
        citiesList.add("Monza")
        citiesList.add("Moose Jaw")
        citiesList.add("Moraira")
        citiesList.add("Moreno Valley")
        citiesList.add("Morgantown")
        citiesList.add("Moroni")
        citiesList.add("Morro Bay")
        citiesList.add("Morzine")
        citiesList.add("Moscow")
        citiesList.add("Mount Vernon")
        citiesList.add("Mountain View")
        citiesList.add("Moutier")
        citiesList.add("Mulhouse")
        citiesList.add("Mumbai")
        citiesList.add("Munich")
        citiesList.add("Münster")
        citiesList.add("Murcia")
        citiesList.add("Murfreesboro")
        citiesList.add("Murter")
        citiesList.add("Mykonos")
        citiesList.add("Mytilene")
        citiesList.add("Nadi")
        citiesList.add("Nafplio")
        citiesList.add("Nagoya")
        citiesList.add("Nags Head")
        citiesList.add("Nairobi")
        citiesList.add("Namur")
        citiesList.add("Nanaimo")
        citiesList.add("Nancy")
        citiesList.add("Nantes")
        citiesList.add("Napa")
        citiesList.add("Naples (Italy)")
        citiesList.add("Naples (U.S.)")
        citiesList.add("Narbonne")
        citiesList.add("Narva")
        citiesList.add("Nashua")
        citiesList.add("Nashville")
        citiesList.add("Nassau")
        citiesList.add("Navarre Beach")
        citiesList.add("Naxos")
        citiesList.add("Nazareth")
        citiesList.add("N'Djamena")
        citiesList.add("Negril")
        citiesList.add("Neiafu")
        citiesList.add("Nelson")
        citiesList.add("Nerja")
        citiesList.add("Netanya")
        citiesList.add("Nevers")
        citiesList.add("New Haven")
        citiesList.add("New London")
        citiesList.add("New Orleans")
        citiesList.add("New Smyrna Beach")
        citiesList.add("New York City")
        citiesList.add("Newark")
        citiesList.add("Newcastle (Australia)")
        citiesList.add("Newcastle (UK)")
        citiesList.add("Newport (UK)")
        citiesList.add("Newport (Rhode Island)")
        citiesList.add("Newport (Vermont)")
        citiesList.add("Newport Beach")
        citiesList.add("Newport News")
        citiesList.add("Newry")
        citiesList.add("Ngerulmud")
        citiesList.add("Nha Trang")
        citiesList.add("Niagara Falls (U.S.)")
        citiesList.add("Niagara Falls (Canada)")
        citiesList.add("Niamey")
        citiesList.add("Nice")
        citiesList.add("Nicosia")
        citiesList.add("Nijmegen")
        citiesList.add("Nimes")
        citiesList.add("Niort")
        citiesList.add("Noosa Heads")
        citiesList.add("Norfolk")
        citiesList.add("Normal")
        citiesList.add("Norman")
        citiesList.add("North Captiva Island")
        citiesList.add("North Las Vegas")
        citiesList.add("North Port")
        citiesList.add("North Topsail Beach")
        citiesList.add("North Wildwood")
        citiesList.add("Norwalk")
        citiesList.add("Norwich")
        citiesList.add("Nottingham")
        citiesList.add("Nouakchott")
        citiesList.add("Novara")
        citiesList.add("Novigrad")
        citiesList.add("Nukuʻalofa")
        citiesList.add("Nukunonu")
        citiesList.add("Nuoro")
        citiesList.add("Nürnberg")
        citiesList.add("Nur-Sultan")
        citiesList.add("Nusa Dua")
        citiesList.add("Nuuk")
        citiesList.add("Nyon")
        citiesList.add("Oak Island")
        citiesList.add("Oakland")
        citiesList.add("Oakville")
        citiesList.add("Oaxaca")
        citiesList.add("Obergurgl")
        citiesList.add("Oberhausen")
        citiesList.add("Ocala")
        citiesList.add("Ocean City")
        citiesList.add("Ocean Grove")
        citiesList.add("Ocean Isle Beach")
        citiesList.add("Oceanside")
        citiesList.add("Ocho Rios")
        citiesList.add("Ocracoke Island")
        citiesList.add("Odense")
        citiesList.add("Odessa")
        citiesList.add("Ogden")
        citiesList.add("Oia")
        citiesList.add("Okaloosa Island")
        citiesList.add("Oklahoma City")
        citiesList.add("Olbia")
        citiesList.add("Oldenburg")
        citiesList.add("Olomouc")
        citiesList.add("Olympia")
        citiesList.add("Omaha")
        citiesList.add("Omoa")
        citiesList.add("Opatija")
        citiesList.add("Orange Beach")
        citiesList.add("Oranjestad (Aruba)")
        citiesList.add("Oranjestad (Sint Eustatius)")
        citiesList.add("Orem")
        citiesList.add("Oristano")
        citiesList.add("Orlando")
        citiesList.add("Orléans")
        citiesList.add("Ortisei")
        citiesList.add("Osaka")
        citiesList.add("Oshawa")
        citiesList.add("Oshkosh")
        citiesList.add("Oslo")
        citiesList.add("Osnabrück")
        citiesList.add("Ostrava")
        citiesList.add("Ottawa")
        citiesList.add("Ouagadougou")
        citiesList.add("Oulu")
        citiesList.add("Ourense")
        citiesList.add("Overland Park")
        citiesList.add("Oviedo")
        citiesList.add("Owensboro")
        citiesList.add("Oxford")
        citiesList.add("Oxnard")
        citiesList.add("Pacific Grove")
        citiesList.add("Padang")
        citiesList.add("Paderborn")
        citiesList.add("Padova")
        citiesList.add("Pago Pago")
        citiesList.add("Palanga")
        citiesList.add("Palavas-les-Flots")
        citiesList.add("Palembang")
        citiesList.add("Palermo")
        citiesList.add("Palikir")
        citiesList.add("Palm Bay")
        citiesList.add("Palm Beach")
        citiesList.add("Palm Springs")
        citiesList.add("Palma de Mallorca")
        citiesList.add("Palma Nova")
        citiesList.add("Palmetto")
        citiesList.add("Palmetto Dunes")
        citiesList.add("Palo Alto")
        citiesList.add("Pamplona")
        citiesList.add("Panama City (U.S.)")
        citiesList.add("Panama City (Panama)")
        citiesList.add("Paphos")
        citiesList.add("Paradiski")
        citiesList.add("Paralia")
        citiesList.add("Paramaribo")
        citiesList.add("Parikia")
        citiesList.add("Paris")
        citiesList.add("Parkersburg")
        citiesList.add("Parksville")
        citiesList.add("Parma")
        citiesList.add("Pärnu")
        citiesList.add("Parris Island")
        citiesList.add("Pasadena")
        citiesList.add("Passo del Tonale")
        citiesList.add("Passo Rolle")
        citiesList.add("Paterson")
        citiesList.add("Patras")
        citiesList.add("Pattaya")
        citiesList.add("Pau")
        citiesList.add("Pavia")
        citiesList.add("Pawleys Island")
        citiesList.add("Peel")
        citiesList.add("Peguera")
        citiesList.add("Pembroke Pines")
        citiesList.add("Peniscola")
        citiesList.add("Pensacola")
        citiesList.add("Pensacola Beach")
        citiesList.add("Peoria")
        citiesList.add("Perast")
        citiesList.add("Perdido Key")
        citiesList.add("Périgueux")
        citiesList.add("Perpignan")
        citiesList.add("Perros-Guirec")
        citiesList.add("Perth (Australia)")
        citiesList.add("Perth (UK)")
        citiesList.add("Perugia")
        citiesList.add("Pesaro")
        citiesList.add("Pescara")
        citiesList.add("Pescasseroli")
        citiesList.add("Petah Tikva")
        citiesList.add("Peterborough")
        citiesList.add("Petra")
        citiesList.add("Petrovac")
        citiesList.add("Pforzheim")
        citiesList.add("Phang Nga")
        citiesList.add("Phetchabun")
        citiesList.add("Philadelphia")
        citiesList.add("Philipsburg")
        citiesList.add("Phoenix")
        citiesList.add("Phuket City")
        citiesList.add("Piacenza")
        citiesList.add("Pierre")
        citiesList.add("Pine Bluff")
        citiesList.add("Pine Knoll Shores")
        citiesList.add("Piraeus")
        citiesList.add("Piran")
        citiesList.add("Pisa")
        citiesList.add("Pistoia")
        citiesList.add("Pittsburgh")
        citiesList.add("Placencia")
        citiesList.add("Plano")
        citiesList.add("Playa Blanca")
        citiesList.add("Playa de las Américas")
        citiesList.add("Playa del Carmen")
        citiesList.add("Pleasure Point")
        citiesList.add("Plovdiv")
        citiesList.add("Plymouth")
        citiesList.add("Plzeň")
        citiesList.add("Podgorica")
        citiesList.add("Point Lookout")
        citiesList.add("Pointe-à-Pitre")
        citiesList.add("Poitiers")
        citiesList.add("Pollença")
        citiesList.add("Pompano Beach")
        citiesList.add("Pontevedra")
        citiesList.add("Pordenone")
        citiesList.add("Poreč")
        citiesList.add("Porlamar")
        citiesList.add("Port Alberni")
        citiesList.add("Port Angeles")
        citiesList.add("Port Charlotte")
        citiesList.add("Port d'Andratx")
        citiesList.add("Port Louis")
        citiesList.add("Port Moresby")
        citiesList.add("Port of Spain")
        citiesList.add("Port Royal Town")
        citiesList.add("Port St. Lucie")
        citiesList.add("Port Townsend")
        citiesList.add("Port Vila")
        citiesList.add("Port-au-Prince")
        citiesList.add("Portimão")
        citiesList.add("Portland (Oregon)")
        citiesList.add("Portland (Maine)")
        citiesList.add("Porto")
        citiesList.add("Porto Cervo")
        citiesList.add("Porto Cristo")
        citiesList.add("Porto Torres")
        citiesList.add("Portocolom")
        citiesList.add("Portoferraio")
        citiesList.add("Portofino")
        citiesList.add("Porto-Novo")
        citiesList.add("Portorož")
        citiesList.add("Porto-Vecchio")
        citiesList.add("Portsmouth (UK)")
        citiesList.add("Portsmouth (U.S.)")
        citiesList.add("Portsmouth Island")
        citiesList.add("Positano")
        citiesList.add("Potenza")
        citiesList.add("Potsdam")
        citiesList.add("Poznan")
        citiesList.add("Pozzuoli")
        citiesList.add("Prague")
        citiesList.add("Praia")
        citiesList.add("Praia da Rocha")
        citiesList.add("Prato")
        citiesList.add("Prescott")
        citiesList.add("Preston")
        citiesList.add("Pretoria")
        citiesList.add("Prince Albert")
        citiesList.add("Prince George")
        citiesList.add("Prince Rupert")
        citiesList.add("Pristina")
        citiesList.add("Propriano")
        citiesList.add("Protaras")
        citiesList.add("Providence")
        citiesList.add("Provincetown")
        citiesList.add("Provo")
        citiesList.add("Pueblo")
        citiesList.add("Puerto Baquerizo Moreno")
        citiesList.add("Puerto Cortés")
        citiesList.add("Puerto de la Cruz")
        citiesList.add("Puerto la Cruz")
        citiesList.add("Puerto Plata")
        citiesList.add("Puerto Princesa")
        citiesList.add("Puerto Rico de Gran Canaria")
        citiesList.add("Puerto Vallarta")
        citiesList.add("Pula")
        citiesList.add("Punta Arenas")
        citiesList.add("Punta Cana")
        citiesList.add("Punta del Este")
        citiesList.add("Punta Gorda")
        citiesList.add("Pyeongchang")
        citiesList.add("Pyongyang")
        citiesList.add("Quarteira")
        citiesList.add("Quebec")
        citiesList.add("Quetzaltenango")
        citiesList.add("Quezon City")
        citiesList.add("Quimper")
        citiesList.add("Quito")
        citiesList.add("Quogue")
        citiesList.add("Rabat")
        citiesList.add("Racine")
        citiesList.add("Ragusa")
        citiesList.add("Railay Beach")
        citiesList.add("Raleigh")
        citiesList.add("Ramallah")
        citiesList.add("Ramsey")
        citiesList.add("Rancho Cucamonga")
        citiesList.add("Randers")
        citiesList.add("Rapallo")
        citiesList.add("Rapid City")
        citiesList.add("Ras al-Khaimah")
        citiesList.add("Ras Sedr")
        citiesList.add("Ratingen")
        citiesList.add("Ravello")
        citiesList.add("Ravenna")
        citiesList.add("Rayong")
        citiesList.add("Reading")
        citiesList.add("Red Deer")
        citiesList.add("Redding")
        citiesList.add("Redondo Beach")
        citiesList.add("Regensburg")
        citiesList.add("Reggio Calabria")
        citiesList.add("Reggio Emilia")
        citiesList.add("Regina")
        citiesList.add("Rehovot")
        citiesList.add("Reims")
        citiesList.add("Rennes")
        citiesList.add("Reno")
        citiesList.add("Rethymno")
        citiesList.add("Reus")
        citiesList.add("Reutlingen")
        citiesList.add("Reykjavik")
        citiesList.add("Rhodes")
        citiesList.add("Richmond")
        citiesList.add("Rieti")
        citiesList.add("Riga")
        citiesList.add("Rijeka")
        citiesList.add("Rimini")
        citiesList.add("Rio de Janeiro")
        citiesList.add("Riomaggiore")
        citiesList.add("Rishon LeZion")
        citiesList.add("Rivas")
        citiesList.add("Riverside")
        citiesList.add("Riviera Maya")
        citiesList.add("Road Town")
        citiesList.add("Roanoke")
        citiesList.add("Rocamadour")
        citiesList.add("Rochester (Minnesota)")
        citiesList.add("Rochester (New York)")
        citiesList.add("Rock Hill")
        citiesList.add("Rockford")
        citiesList.add("Rockville (Maryland)")
        citiesList.add("Rockville (South Carolina)")
        citiesList.add("Rodanthe")
        citiesList.add("Rodez")
        citiesList.add("Rogers")
        citiesList.add("Rome")
        citiesList.add("Ronda")
        citiesList.add("Rosario")
        citiesList.add("Roseau")
        citiesList.add("Roskilde")
        citiesList.add("Rostock")
        citiesList.add("Roswell")
        citiesList.add("Rotterdam")
        citiesList.add("Roubaix")
        citiesList.add("Rouen")
        citiesList.add("Rovigo")
        citiesList.add("Rovinj")
        citiesList.add("Rutland")
        citiesList.add("Sa Coma")
        citiesList.add("Sa Pobla")
        citiesList.add("Saalbach")
        citiesList.add("Saarbrücken")
        citiesList.add("Saas-Fee")
        citiesList.add("Sacramento")
        citiesList.add("Safaga")
        citiesList.add("Sag Harbor")
        citiesList.add("Sagaponack")
        citiesList.add("Saguenay")
        citiesList.add("Saint John")
        citiesList.add("Saint Paul")
        citiesList.add("Saint Petersburg")
        citiesList.add("Saint-Brieuc")
        citiesList.add("Sainte-Maxime")
        citiesList.add("Saintes-Maries-de-la-Mer")
        citiesList.add("Saint-Étienne")
        citiesList.add("Saint-Jean-Cap-Ferrat")
        citiesList.add("Saint-Jean-sur-Richelieu")
        citiesList.add("Saint-Jérôme")
        citiesList.add("Saint-Laurent-du-Maroni")
        citiesList.add("Saint-Malo")
        citiesList.add("Saint-Tropez")
        citiesList.add("Salamanca")
        citiesList.add("Salem (Oregon)")
        citiesList.add("Salem (Massachusetts)")
        citiesList.add("Salerno")
        citiesList.add("Salinas")
        citiesList.add("Salisbury")
        citiesList.add("Salou")
        citiesList.add("Salt Lake City")
        citiesList.add("Salta")
        citiesList.add("Salter Path")
        citiesList.add("Salvador")
        citiesList.add("Salvo")
        citiesList.add("Salzburg")
        citiesList.add("Samaná")
        citiesList.add("San Angelo")
        citiesList.add("San Antonio")
        citiesList.add("San Bernardino")
        citiesList.add("San Clemente")
        citiesList.add("San Cristóbal")
        citiesList.add("San Diego")
        citiesList.add("San Fernando")
        citiesList.add("San Francisco")
        citiesList.add("San José (Costa Rica)")
        citiesList.add("San Jose (U.S.)")
        citiesList.add("San Juan")
        citiesList.add("San Juan del Sur")
        citiesList.add("San Lorenzo")
        citiesList.add("San Luis Obispo")
        citiesList.add("San Marino")
        citiesList.add("San Mateo")
        citiesList.add("San Miguel")
        citiesList.add("San Pedro")
        citiesList.add("San Pedro de Atacama")
        citiesList.add("San Pedro Sula")
        citiesList.add("San Rafael")
        citiesList.add("San Salvador")
        citiesList.add("San Sebastián")
        citiesList.add("Sanaa")
        citiesList.add("Sandbridge")
        citiesList.add("Sanford")
        citiesList.add("Sanibel Island")
        citiesList.add("Sanremo")
        citiesList.add("Sant Antoni de Portmany")
        citiesList.add("Santa Ana (U.S.)")
        citiesList.add("Santa Ana (El Salvador)")
        citiesList.add("Santa Barbara")
        citiesList.add("Santa Clara")
        citiesList.add("Santa Clarita")
        citiesList.add("Santa Cruz")
        citiesList.add("Santa Cruz de la Sierra")
        citiesList.add("Santa Cruz de Tenerife")
        citiesList.add("Santa Eulària des Riu")
        citiesList.add("Santa Fe")
        citiesList.add("Santa Lucía")
        citiesList.add("Santa Margherita Ligure")
        citiesList.add("Santa Maria (Cape Verde)")
        citiesList.add("Santa Maria (U.S.)")
        citiesList.add("Santa Monica")
        citiesList.add("Santa Pola")
        citiesList.add("Santa Ponsa")
        citiesList.add("Santa Rosa")
        citiesList.add("Santa Tecla")
        citiesList.add("Santander")
        citiesList.add("Santanyí")
        citiesList.add("Santiago (Chile)")
        citiesList.add("Santiago (Dominican Rep.)")
        citiesList.add("Santiago de Compostela")
        citiesList.add("Santo Domingo")
        citiesList.add("Sanur")
        citiesList.add("Sao Paulo")
        citiesList.add("São Tomé")
        citiesList.add("Sapporo")
        citiesList.add("Sarajevo")
        citiesList.add("Sarasota")
        citiesList.add("Saratoga Springs")
        citiesList.add("S'Arenal")
        citiesList.add("Sariaya")
        citiesList.add("Sarlat-la-Canéda")
        citiesList.add("Saskatoon")
        citiesList.add("Sassari")
        citiesList.add("Sault Ste. Marie")
        citiesList.add("Saumur")
        citiesList.add("Savannah")
        citiesList.add("Savona")
        citiesList.add("Savusavu")
        citiesList.add("Schaffhausen")
        citiesList.add("Schenectady")
        citiesList.add("Schladming")
        citiesList.add("Scottsdale")
        citiesList.add("Scranton")
        citiesList.add("Sea Island")
        citiesList.add("Sea Isle City")
        citiesList.add("Seabrook Island")
        citiesList.add("Seal Beach")
        citiesList.add("Seaside")
        citiesList.add("Seattle")
        citiesList.add("Sedona")
        citiesList.add("Seefeld")
        citiesList.add("Segovia")
        citiesList.add("Semarang")
        citiesList.add("Seminyak")
        citiesList.add("Seoul")
        citiesList.add("Serre Chevalier")
        citiesList.add("Sète")
        citiesList.add("Seville")
        citiesList.add("Shanghai")
        citiesList.add("Sharjah")
        citiesList.add("Sharm el-Sheikh")
        citiesList.add("Sheffield")
        citiesList.add("Shell Point")
        citiesList.add("Shelter Cove")
        citiesList.add("Shenzhen")
        citiesList.add("Sherbrooke")
        citiesList.add("Shinnecock Hills")
        citiesList.add("Ship Bottom")
        citiesList.add("Shreveport")
        citiesList.add("Šiauliai")
        citiesList.add("Šibenik")
        citiesList.add("Side")
        citiesList.add("Siegen")
        citiesList.add("Siena")
        citiesList.add("Siesta Key")
        citiesList.add("Sineu")
        citiesList.add("Singapore")
        citiesList.add("Singaraja")
        citiesList.add("Sion")
        citiesList.add("Sioux City")
        citiesList.add("Sioux Falls")
        citiesList.add("Sitges")
        citiesList.add("Skiathos")
        citiesList.add("Skopje")
        citiesList.add("Sofia")
        citiesList.add("Sölden")
        citiesList.add("Söll")
        citiesList.add("Soller")
        citiesList.add("Solothurn")
        citiesList.add("Sondrio")
        citiesList.add("Sopot")
        citiesList.add("Sorocaba")
        citiesList.add("Sorrento")
        citiesList.add("South Beach")
        citiesList.add("South Bend")
        citiesList.add("Southampton (UK)")
        citiesList.add("Southampton (New York)")
        citiesList.add("Southern Shores")
        citiesList.add("Split")
        citiesList.add("Spokane")
        citiesList.add("Springdale")
        citiesList.add("Springfield (Illinois)")
        citiesList.add("Springfield (Massachusetts)")
        citiesList.add("Springfield (Missouri)")
        citiesList.add("Springfield (Oregon)")
        citiesList.add("Springs")
        citiesList.add("St Albans")
        citiesList.add("St George's (Bermuda)")
        citiesList.add("St Pete Beach")
        citiesList.add("St. Albans")
        citiesList.add("St. Anton")
        citiesList.add("St. Augustine")
        citiesList.add("St. Catharines")
        citiesList.add("St. Cloud")
        citiesList.add("St. Gallen")
        citiesList.add("St. George")
        citiesList.add("St. George Island")
        citiesList.add("St. George's (Grenada)")
        citiesList.add("St. John's (Antigua and Barbuda)")
        citiesList.add("St. John's (Canada)")
        citiesList.add("St. Louis")
        citiesList.add("St. Moritz")
        citiesList.add("St. Petersburg (U.S.)")
        citiesList.add("St. Simons Island")
        citiesList.add("Stamford")
        citiesList.add("Stanley")
        citiesList.add("Stavanger")
        citiesList.add("Steinbach")
        citiesList.add("Stillwater")
        citiesList.add("Stirling")
        citiesList.add("Stock Island")
        citiesList.add("Stockholm")
        citiesList.add("Stockton")
        citiesList.add("Stoke-on-Trent")
        citiesList.add("Stone Harbor")
        citiesList.add("Strasbourg")
        citiesList.add("Strathmere")
        citiesList.add("Stuttgart")
        citiesList.add("Sucre")
        citiesList.add("Sudbury")
        citiesList.add("Suez")
        citiesList.add("Sukhothai")
        citiesList.add("Sukhumi")
        citiesList.add("Sullivan's Island")
        citiesList.add("Summerside")
        citiesList.add("Sumter")
        citiesList.add("Sunderland")
        citiesList.add("Sunnyvale")
        citiesList.add("Sunset Beach")
        citiesList.add("Sunshine Coast")
        citiesList.add("Superior")
        citiesList.add("Surabaya")
        citiesList.add("Surf City (New Jersey)")
        citiesList.add("Surf City (North Carolina)")
        citiesList.add("Surrey")
        citiesList.add("Suva")
        citiesList.add("Sveti Stefan")
        citiesList.add("Swansea")
        citiesList.add("Sydney (Australia)")
        citiesList.add("Sydney (Canada)")
        citiesList.add("Syracuse (Italy)")
        citiesList.add("Syracuse (U.S.)")
        citiesList.add("Szczecin")
        citiesList.add("Taba")
        citiesList.add("Tacloban")
        citiesList.add("Tacoma")
        citiesList.add("Tagbilaran")
        citiesList.add("Taipei")
        citiesList.add("Tallahassee")
        citiesList.add("Tallinn")
        citiesList.add("Tampa")
        citiesList.add("Tampere")
        citiesList.add("Tamworth")
        citiesList.add("Tangier")
        citiesList.add("Taormina")
        citiesList.add("Taranto")
        citiesList.add("Tarifa")
        citiesList.add("Tarragona")
        citiesList.add("Tartu")
        citiesList.add("Tashkent")
        citiesList.add("Tauplitz")
        citiesList.add("Tauranga")
        citiesList.add("Tavira")
        citiesList.add("Tbilisi")
        citiesList.add("Tegucigalpa")
        citiesList.add("Tel Aviv")
        citiesList.add("Temecula")
        citiesList.add("Tempe")
        citiesList.add("Teramo")
        citiesList.add("Ternate")
        citiesList.add("Terni")
        citiesList.add("Texarkana AR")
        citiesList.add("Texarkana TX")
        citiesList.add("The Bottom")
        citiesList.add("The Hague")
        citiesList.add("The Valley")
        citiesList.add("The Wildwoods")
        citiesList.add("The Woodlands")
        citiesList.add("Thessaloniki")
        citiesList.add("Thimphu")
        citiesList.add("Thunder Bay")
        citiesList.add("Tignes")
        citiesList.add("Tijuana")
        citiesList.add("Tilburg")
        citiesList.add("Timmins")
        citiesList.add("Tinos")
        citiesList.add("Tirana")
        citiesList.add("Tivat")
        citiesList.add("Tivoli")
        citiesList.add("Tokyo")
        citiesList.add("Toledo (Spain)")
        citiesList.add("Toledo (U.S.)")
        citiesList.add("Tooele")
        citiesList.add("Toowoomba")
        citiesList.add("Topeka")
        citiesList.add("Topsail Beach")
        citiesList.add("Toronto")
        citiesList.add("Torre del Greco")
        citiesList.add("Torre del Mar")
        citiesList.add("Torremolinos")
        citiesList.add("Torrevieja")
        citiesList.add("Tórshavn")
        citiesList.add("Toruń")
        citiesList.add("Tossa de Mar")
        citiesList.add("Toulon")
        citiesList.add("Toulouse")
        citiesList.add("Tours")
        citiesList.add("Townsville")
        citiesList.add("Trani")
        citiesList.add("Trapani")
        citiesList.add("Treasure Island")
        citiesList.add("Trento")
        citiesList.add("Trenton")
        citiesList.add("Treviso")
        citiesList.add("Trier")
        citiesList.add("Trieste")
        citiesList.add("Tripoli")
        citiesList.add("Trogir")
        citiesList.add("Trois-Rivières")
        citiesList.add("Tromsø")
        citiesList.add("Trondheim")
        citiesList.add("Trouville-sur-Mer")
        citiesList.add("Troy")
        citiesList.add("Troyes")
        citiesList.add("Trujillo")
        citiesList.add("Tucson")
        citiesList.add("Tui")
        citiesList.add("Tulsa")
        citiesList.add("Tulum")
        citiesList.add("Turin")
        citiesList.add("Turku")
        citiesList.add("Tuscaloosa")
        citiesList.add("Twin Falls")
        citiesList.add("Two Harbors")
        citiesList.add("Tybee Island")
        citiesList.add("Tyler")
        citiesList.add("Ubud")
        citiesList.add("Udine")
        citiesList.add("Udon Thani")
        citiesList.add("Ukiah")
        citiesList.add("Ulaanbaatar")
        citiesList.add("Ulcinj")
        citiesList.add("Ulm")
        citiesList.add("Umag")
        citiesList.add("Uppsala")
        citiesList.add("Urbino")
        citiesList.add("Urubamba")
        citiesList.add("Ushuaia")
        citiesList.add("Utica")
        citiesList.add("Utrecht")
        citiesList.add("Vaduz")
        citiesList.add("Val d’Isère")
        citiesList.add("Val di Fassa")
        citiesList.add("Val Gardena")
        citiesList.add("Val Thorens")
        citiesList.add("Valence")
        citiesList.add("Valencia (Spain)")
        citiesList.add("Valencia (Venezuela)")
        citiesList.add("Valladolid")
        citiesList.add("Valldemossa")
        citiesList.add("Valle Isarco")
        citiesList.add("Valletta")
        citiesList.add("Valparaíso")
        citiesList.add("Vancouver (Canada)")
        citiesList.add("Vancouver (U.S.)")
        citiesList.add("Varazze")
        citiesList.add("Varese")
        citiesList.add("Varna")
        citiesList.add("Vaughan")
        citiesList.add("Vejle")
        citiesList.add("Venice (Italy)")
        citiesList.add("Venice (U.S.)")
        citiesList.add("Ventimiglia")
        citiesList.add("Ventnor City")
        citiesList.add("Ventspils")
        citiesList.add("Ventura")
        citiesList.add("Verbania")
        citiesList.add("Verbier")
        citiesList.add("Vercelli")
        citiesList.add("Vero Beach")
        citiesList.add("Verona")
        citiesList.add("Versailles")
        citiesList.add("Vevey")
        citiesList.add("Viareggio")
        citiesList.add("Vibo Valentia")
        citiesList.add("Viborg")
        citiesList.add("Vicenza")
        citiesList.add("Vichy")
        citiesList.add("Victoria (Canada)")
        citiesList.add("Victoria (Seychelles)")
        citiesList.add("Victorville")
        citiesList.add("Vienna")
        citiesList.add("Vigan")
        citiesList.add("Vigo")
        citiesList.add("Vilamoura")
        citiesList.add("Villach")
        citiesList.add("Villefranche-sur-Mer")
        citiesList.add("Vilnius")
        citiesList.add("Viña del Mar")
        citiesList.add("Virginia Beach")
        citiesList.add("Visalia")
        citiesList.add("Viterbo")
        citiesList.add("Vitoria-Gasteiz")
        citiesList.add("Volos")
        citiesList.add("Vrsar")
        citiesList.add("")
        citiesList.add("Waco")
        citiesList.add("Wainscott")
        citiesList.add("Wakefield")
        citiesList.add("Wanchese")
        citiesList.add("Warsaw")
        citiesList.add("Warth")
        citiesList.add("Washington D.C.")
        citiesList.add("Water Mill")
        citiesList.add("Waterford")
        citiesList.add("Watertown")
        citiesList.add("Watsonville")
        citiesList.add("Waukegan")
        citiesList.add("Waukesha")
        citiesList.add("Waves")
        citiesList.add("Wellington (New Zealand)")
        citiesList.add("Wellington (U.S.)")
        citiesList.add("Wengen")
        citiesList.add("Weno")
        citiesList.add("West Hampton Dunes")
        citiesList.add("West Lafayette")
        citiesList.add("West Palm Beach")
        citiesList.add("West Wildwood")
        citiesList.add("Westendorf")
        citiesList.add("Westhampton")
        citiesList.add("Westhampton Beach")
        citiesList.add("Westminster")
        citiesList.add("Weston")
        citiesList.add("Wheeling")
        citiesList.add("White Plains")
        citiesList.add("Whitehorse")
        citiesList.add("Wichita")
        citiesList.add("Wichita Falls")
        citiesList.add("Wiesbaden")
        citiesList.add("Wildwood")
        citiesList.add("Wildwood Crest")
        citiesList.add("Wilkes-Barre")
        citiesList.add("Willemstad")
        citiesList.add("Williams")
        citiesList.add("Wilmington (Delaware)")
        citiesList.add("Wilmington (North Carolina)")
        citiesList.add("Winchester")
        citiesList.add("Windhoek")
        citiesList.add("Windsor")
        citiesList.add("Winnipeg")
        citiesList.add("Winslow")
        citiesList.add("Winston–Salem")
        citiesList.add("Winterthur")
        citiesList.add("Wolfsburg")
        citiesList.add("Wollongong")
        citiesList.add("Wolverhampton")
        citiesList.add("Woodburn")
        citiesList.add("Worcester (UK)")
        citiesList.add("Worcester (U.S.)")
        citiesList.add("Worthing")
        citiesList.add("Wrightsville Beach")
        citiesList.add("Wroclaw")
        citiesList.add("Wuppertal")
        citiesList.add("Würzburg")
        citiesList.add("Yakima")
        citiesList.add("Yamoussoukro")
        citiesList.add("Yaoundé")
        citiesList.add("Yaren")
        citiesList.add("Yellowknife")
        citiesList.add("Yerevan")
        citiesList.add("Yogyakarta")
        citiesList.add("Yokohama")
        citiesList.add("Yonkers")
        citiesList.add("York (UK)")
        citiesList.add("York (U.S.)")
        citiesList.add("Youngstown")
        citiesList.add("Yuma")
        citiesList.add("Zadar")
        citiesList.add("Zagreb")
        citiesList.add("Zakopane")
        citiesList.add("Zamboanga City")
        citiesList.add("Zanzibar")
        citiesList.add("Zaragoza")
        citiesList.add("Zell am See")
        citiesList.add("Zell am Ziller")
        citiesList.add("Zermatt")
        citiesList.add("Zug")
        citiesList.add("Zurich")
        citiesList.add("Zwickau")
        citiesList.add("Zwolle")
        citiesList.add("")





        return citiesList
    }

}